/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIYonetim;
import com.oybak.otel.Yonetim;
import com.oybak.otel.enums.UserRole;
import javax.swing.JOptionPane;
import com.oybak.otel.Personel;
/**
 *
 * @author userxpc666
 */
public class CalisanEkle extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalisanEkle.class.getName());

    /**
     * Creates new form CalisanEkle
     */
    private UserRole aktifRol;
    private String teknikUzmanlik = "";
    
    public CalisanEkle(UserRole rol) {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
        this.aktifRol=rol;
    }
    
    // CalisanEkle.java dosyasının içinde bir yere:

private void personelKaydet(String uzmanlikAlani) {
    try {
        // 1. Verileri jTextPane'lerden çekiyoruz
        // Sıralama: 1:İsim, 2:Soyisim, 3:Maaş, 4:TC, 5:Şifre
        String ad = jTextPane1.getText().trim();
        String soyad = jTextPane2.getText().trim();
        String maasStr = jTextPane3.getText().trim();
        String tcStr = jTextPane4.getText().trim();
        String sifre = jTextPane5.getText().trim();

        // 2. Boşluk Kontrolü
        if (ad.isEmpty() || soyad.isEmpty() || maasStr.isEmpty() || tcStr.isEmpty() || sifre.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen tüm alanları eksiksiz doldurunuz!", "Eksik Bilgi", 2);
            return;
        }

        // 3. TC Hane ve Tip Kontrolü (Long)
        if (tcStr.length() != 11) {
            javax.swing.JOptionPane.showMessageDialog(this, "TC Kimlik No 11 haneli olmalıdır!", "Hata", 0);
            return;
        }
        long tc = Long.parseLong(tcStr); // 11 hane için long şart

        // 4. Mükerrer Kayıt Kontrolü (UNIQUE kısıtlaması için ön kontrol)
        // Not: Yonetim sınıfındaki tcVarMi metodunu kullandığını varsayıyoruz.
        Yonetim yonetici = new Yonetim("Admin", "Sistem", 0L, 0.0, "Yonetim");
        if (yonetici.tcVarMi(tc)) {
            javax.swing.JOptionPane.showMessageDialog(this, "Bu TC numarası veritabanında zaten kayıtlı!", "Mükerrer Kayıt", 0);
            return;
        }

        // 5. Maaş Dönüşümü
        double maas = Double.parseDouble(maasStr);

        // 6. Personel Nesnesini Oluşturma
        // Constructor sırası: ad, soyad, tc, maas, uzmanlikAlani
        Personel yeniKisi = new Personel(ad, soyad, tc, maas, uzmanlikAlani);

        // 7. Veritabanına Kayıt (yonetici içindeki personelEkle metodunu çağırıyoruz)
        // Eğer veritabanında şifreyi de ayrı tutuyorsan, metoduna şifreyi de eklemelisin.
        yonetici.personelEkle(yeniKisi); 

        // 8. Başarı Mesajı ve Formu Temizleme
        javax.swing.JOptionPane.showMessageDialog(this, "Personel başarıyla kaydedildi!");
        
        jTextPane1.setText("");
        jTextPane2.setText("");
        jTextPane3.setText("");
        jTextPane4.setText("");
        jTextPane5.setText("");

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "TC ve Maaş alanlarına sadece sayı girmelisiniz!", "Format Hatası", 0);
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Beklenmedik bir hata oluştu: " + e.getMessage(), "Hata", 0);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextPane4 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Yeni Çalışan Bilgilerini Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 32, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel2.setText("İsim Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 26, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel3.setText("Soy İsim Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jLabel3, gridBagConstraints);

        jLabel4.setText("Maaş Giriniz (TL)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jScrollPane4.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        jScrollPane5.setViewportView(jTextPane2);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(jScrollPane5, gridBagConstraints);

        jScrollPane6.setViewportView(jTextPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(jScrollPane6, gridBagConstraints);

        jLabel5.setText("İş Tipi Seçiniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jLabel5, gridBagConstraints);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Yönetici", "Teknik Personel", "Resepsiyon" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(jComboBox1, gridBagConstraints);

        jLabel6.setText("TC Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jLabel6, gridBagConstraints);

        jScrollPane7.setViewportView(jTextPane4);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 0, 0);
        getContentPane().add(jScrollPane7, gridBagConstraints);

        jButton2.setText("Kaydet");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(49, 27, 8, 6);
        getContentPane().add(jButton2, gridBagConstraints);

        jLabel7.setText("Çalışanın Şifresini Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jLabel7, gridBagConstraints);

        jScrollPane8.setViewportView(jTextPane5);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 48;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(12, 26, 0, 0);
        getContentPane().add(jScrollPane8, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        com.oybak.otel.GUIYonetim.YonetimCalisan Calisan = new com.oybak.otel.GUIYonetim.YonetimCalisan(aktifRol);
       
       Calisan.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   String secilenIs = jComboBox1.getSelectedItem().toString();

    if (secilenIs.equals("Seçiniz")) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lütfen bir iş tipi seçiniz!");
        return;
    }

    if (secilenIs.equals("Teknik Personel")) {
        // Pop-up ile uzmanlık alanını alıyoruz
        String input = javax.swing.JOptionPane.showInputDialog(this, 
                "Teknik Personelin Uzmanlık Alanını Giriniz:", 
                "Uzmanlık Bilgisi", 
                javax.swing.JOptionPane.QUESTION_MESSAGE);

        if (input != null && !input.trim().isEmpty()) {
            this.teknikUzmanlik = input; // Alınan bilgiyi değişkene kaydediyoruz
        } else {
            // İptal edilirse seçimi sıfırla
            jComboBox1.setSelectedIndex(0);
            this.teknikUzmanlik = "";
        }
    } else {
        // Teknik personel dışındakiler için uzmanlık bilgisini temizle
        
        this.teknikUzmanlik = "";
    }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String secilenIs = jComboBox1.getSelectedItem().toString();

    // 1. İş tipi seçilmemişse veya "Seçiniz"de kalmışsa
    if (secilenIs.equals("Seçiniz")) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Lütfen Bilgileri Eksiksiz Giriniz!", 
                "Eksik Bilgi", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // 2. Teknik personel seçilmiş ama pop-up'a cevap verilmemişse
    if (secilenIs.equals("Teknik Personel") && (teknikUzmanlik == null || teknikUzmanlik.isEmpty())) {
        javax.swing.JOptionPane.showMessageDialog(this, 
                "Lütfen Bilgileri Eksiksiz Giriniz!", 
                "Eksik Bilgi", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // Her şey tamamsa kayıt metodunu çağır
    if (secilenIs.equals("Teknik Personel")) {
        personelKaydet(teknikUzmanlik);
    } else {
        personelKaydet(secilenIs);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
java.awt.EventQueue.invokeLater(() -> {
    
    new CalisanEkle(UserRole.YONETIM).setVisible(true); 
});
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextPane jTextPane4;
    private javax.swing.JTextPane jTextPane5;
    // End of variables declaration//GEN-END:variables
}
