/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIYonetim;
import com.oybak.otel.Personel;
import com.oybak.otel.enums.UserRole;
import com.oybak.otel.VeriTabani;
import com.oybakotel.GUI.GeriButonu;

/**
 *
 * @author userxpc666
 */
public class GecmisMusteriler extends javax.swing.JFrame implements VeriTabani, GeriButonu {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GecmisMusteriler.class.getName());

    /**
     * Creates new form GecmisMusteriler
     */
    private Personel p;
    
    public GecmisMusteriler(Personel p) {
        initComponents();
        this.p=p;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSonucAlani = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("İsim Soyisim:");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        txtSonucAlani.setColumns(20);
        txtSonucAlani.setLineWrap(true);
        txtSonucAlani.setRows(5);
        txtSonucAlani.setText("Aranan Müşterinin Bilgileri:");
        txtSonucAlani.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSonucAlaniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSonucAlaniFocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txtSonucAlani);

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Aranacak müşterinin isim soyismini giriniz:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
       if (jTextField1.getText().equals("İsim Soyisim:")) {
        jTextField1.setText("");
    }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().isEmpty()) {
        jTextField1.setText("İsim Soyisim:");
    }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        String arananIsim = jTextField1.getText().replace("İsim Soyisim:", "").trim();

    if (arananIsim.isEmpty()) {
        txtSonucAlani.setText("Lütfen bir isim giriniz.");
        return;
    }

    txtSonucAlani.setText(""); // Eski sonuçları temizle
    // SQL sorgusu: geçmiş müşteriler tablosundan isimle arama yapıyoruz
    String sql = "SELECT ad_soyad, tc_no, oda_no, giris_tarihi, cikis_tarihi, kasa_katki FROM gecmis_musteriler WHERE ad_soyad LIKE ?";

    try (java.sql.Connection conn = java.sql.DriverManager.getConnection(URL);
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {

        pstmt.setString(1, "%" + arananIsim + "%");
        java.sql.ResultSet rs = pstmt.executeQuery();

        boolean bulundu = false;
        StringBuilder sb = new StringBuilder();

        while (rs.next()) {
            bulundu = true;
            sb.append("Müşteri Ad Soyad: ").append(rs.getString("ad_soyad")).append("\n")
              .append("TC Kimlik No: ").append(rs.getString("tc_no")).append("\n") // Yönetim olduğu için TC ekliyoruz
              .append("Oda Numarası: ").append(rs.getString("oda_no")).append("\n")
              .append("Giriş Tarihi: ").append(rs.getString("giris_tarihi")).append("\n")
              .append("Çıkış Tarihi: ").append(rs.getString("cikis_tarihi")).append("\n")
              .append("Kasaya Katkı: ").append(rs.getInt("kasa_katki")).append(" TL\n")
              .append("-------------------------------------------\n");
        }

        if (bulundu) {
            txtSonucAlani.setText(sb.toString());
        } else {
            txtSonucAlani.setText("Sistemde '" + arananIsim + "' isminde bir geçmiş kayıt bulunamadı.");
        }

    } catch (java.sql.SQLException e) {
        txtSonucAlani.setText("Veritabanı hatası: " + e.getMessage());
    }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void txtSonucAlaniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSonucAlaniFocusGained

    }//GEN-LAST:event_txtSonucAlaniFocusGained

    private void txtSonucAlaniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSonucAlaniFocusLost

    }//GEN-LAST:event_txtSonucAlaniFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       geriButonu(p);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Personel p = new Personel("Test", 12345678916L, 0, null, "123");
            new YonetimMusteriArama(p).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtSonucAlani;
    // End of variables declaration//GEN-END:variables
}
