/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIYonetim;
import com.oybak.otel.enums.UserRole;
import com.oybak.otel.VeriTabani;
/**
 *
 * @author userxpc666
 */
public class ParaIade extends javax.swing.JFrame implements VeriTabani {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParaIade.class.getName());

    /**
     * Creates new form Paraİade
     */
    private UserRole aktifRol;
    public ParaIade(UserRole rol) {
        initComponents();
        this.aktifRol=rol;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(19, 14, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Para İadesi Yapılacak Müşterinin Bilgilerini Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = -22;
        gridBagConstraints.insets = new java.awt.Insets(6, 14, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        jScrollPane1.setViewportView(jTextPane1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("İsim ve Soy İsim Giriniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 0, 0);
        getContentPane().add(jLabel2, gridBagConstraints);

        jLabel4.setText("Para Miktarı Giriniz (TL)");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(12, 24, 0, 0);
        getContentPane().add(jLabel4, gridBagConstraints);

        jScrollPane3.setViewportView(jTextPane3);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 360;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 24, 0, 0);
        getContentPane().add(jScrollPane3, gridBagConstraints);

        jButton2.setText("İade Yap");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(34, 171, 6, 0);
        getContentPane().add(jButton2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        com.oybak.otel.GUIYonetim.YonetimKasa Kasa = new com.oybak.otel.GUIYonetim.YonetimKasa(aktifRol);
       
       Kasa.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // Kullanıcının girdiği verileri alıyoruz
    String adSoyad = jTextPane1.getText().trim();
    String iadeMiktariStr = jTextPane3.getText().trim();

    // 1. Boş alan kontrolü
    if (adSoyad.isEmpty() || iadeMiktariStr.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lütfen isim ve miktar alanlarını doldurunuz!", "Eksik Bilgi", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        // Virgül girilirse noktaya çevirip sayıya dönüştürüyoruz
        double iadeMiktari = Double.parseDouble(iadeMiktariStr.replace(",", "."));
        
        if (iadeMiktari <= 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "İade miktarı 0'dan büyük olmalıdır!", "Hatalı Miktar", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 2. Kontrol Sorgusu: Müşteri var mı ve bakiyesi yetiyor mu?
        String kontrolSql = "SELECT kasa_katki FROM guncel_musteriler WHERE ad_soyad = ?";
        
        // Yonetim class'ındaki gibi VeriTabani.URL kullanıyoruz
        try (java.sql.Connection conn = java.sql.DriverManager.getConnection(VeriTabani.URL);
             java.sql.PreparedStatement pstmtKontrol = conn.prepareStatement(kontrolSql)) {
            
            pstmtKontrol.setString(1, adSoyad);
            java.sql.ResultSet rs = pstmtKontrol.executeQuery();

            if (rs.next()) {
                double mevcutBakiye = rs.getDouble("kasa_katki");

                // 3. Mantıksal Kontrol: Ödenen paradan fazla iade yapılamaz
                if (iadeMiktari > mevcutBakiye) {
                    javax.swing.JOptionPane.showMessageDialog(this, 
                        "HATA: Müşterinin toplam ödemesi " + mevcutBakiye + " TL.\nBundan daha yüksek bir iade yapamazsınız!", 
                        "Yetersiz Bakiye", javax.swing.JOptionPane.ERROR_MESSAGE);
                } else {
                    // 4. Güncelleme Sorgusu: Parayı düşüyoruz
                    String guncelleSql = "UPDATE guncel_musteriler SET kasa_katki = kasa_katki - ? WHERE ad_soyad = ?";
                    try (java.sql.PreparedStatement pstmtGuncelle = conn.prepareStatement(guncelleSql)) {
                        pstmtGuncelle.setDouble(1, iadeMiktari);
                        pstmtGuncelle.setString(2, adSoyad);
                        
                        int sonuc = pstmtGuncelle.executeUpdate();
                        if (sonuc > 0) {
                            javax.swing.JOptionPane.showMessageDialog(this, 
                                "BAŞARILI: " + adSoyad + " isimli müşteriye " + iadeMiktari + " TL iade edildi.\nGüncel Bakiye: " + (mevcutBakiye - iadeMiktari) + " TL", 
                                "İşlem Tamamlandı", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                            
                            // Kutuları temizle
                            jTextPane1.setText("");
                            jTextPane3.setText("");
                        }
                    }
                }
            } else {
                // İsim veritabanında yoksa
                javax.swing.JOptionPane.showMessageDialog(this, "UYARI: '" + adSoyad + "' isminde güncel bir müşteri kaydı bulunamadı!", "Kayıt Yok", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lütfen miktar alanına geçerli bir sayı giriniz!", "Format Hatası", javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "VERİTABANI HATASI: " + e.getMessage(), "Hata", javax.swing.JOptionPane.ERROR_MESSAGE);
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
    
    new ParaIade(UserRole.YONETIM).setVisible(true); 
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}
