/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIYonetim;
import com.oybak.otel.Personel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.oybak.otel.VeriTabani;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import com.oybakotel.GUI.GeriButonu;

/**
 *
 * @author userxpc666
 * y
 */
public class YonetimOdaOzellik extends javax.swing.JFrame implements VeriTabani,GeriButonu {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(YonetimOdaOzellik.class.getName());

    /**
     * Creates new form YonetimOdaOzellik
     */
    private Personel p;
    
    public YonetimOdaOzellik(Personel p) {
        initComponents();
        this.p=p;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
       jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextField1.getText().equals("Oda Numarası:")) jTextField1.setText("");
    }
});
// Formu sıfırlamak için yardımcı metod (Bunu class içinde uygun bir yere koy)

// Fiyat kutusuna tıklayınca yazıyı siler
jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
    @Override
    public void focusGained(java.awt.event.FocusEvent evt) {
        if (jTextField2.getText().equals("Fiyat:")) jTextField2.setText("");
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Kaydet");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Oda Bilgileri:");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("Oda Numarası:");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "0", "1", "2", "3" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "0", "1", "2", "3" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));

        jLabel1.setText("Tek Kişilik Yatak");

        jLabel2.setText("Çift Kişilik Yatak");

        jLabel3.setText("Deniz Manzarasi");

        jLabel4.setText("Balkon");

        jLabel5.setText("Jakuzi");

        jLabel8.setText("Fiyat (TL)");

        jTextField2.setText("Fiyat:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        geriButonu(p);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
      String odaNo = jTextField1.getText().trim();

    if (odaNo.isEmpty() || odaNo.equals("Oda Numarası:")) {
        jTextArea1.setText("Oda Bilgileri:");
        return;
    }

    try (Connection con = DriverManager.getConnection(URL)) {
        String query = "SELECT * FROM odalar WHERE oda_no = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, odaNo);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // --- GÜVENLİ OKUMA YÖNTEMİ ---
            // getString kullanarak hem "true" metnini hem de "1" değerini yakalıyoruz
            String dbManzara = String.valueOf(rs.getObject("deniz_manzarasi"));
            String dbBalkon = String.valueOf(rs.getObject("balkon"));
            String dbJakuzi = String.valueOf(rs.getObject("jakuzi"));

            // Değer "true" veya "1" ise "Var", değilse "Yok" yaz
            String dManzara = (dbManzara.equalsIgnoreCase("true") || dbManzara.equals("1")) ? "Var" : "Yok";
            String balkon = (dbBalkon.equalsIgnoreCase("true") || dbBalkon.equals("1")) ? "Var" : "Yok";
            String jakuzi = (dbJakuzi.equalsIgnoreCase("true") || dbJakuzi.equals("1")) ? "Var" : "Yok";

            String bilgiler = "Oda No: " + rs.getInt("oda_no") + "\n"
                            + "Tek Kişilik Yatak: " + rs.getInt("tek_kisilik_yatak") + "\n"
                            + "Çift Kişilik Yatak: " + rs.getInt("cift_kisilik_yatak") + "\n"
                            + "Deniz Manzarası: " + dManzara + "\n"
                            + "Balkon: " + balkon + "\n"
                            + "Jakuzi: " + jakuzi + "\n"
                            + "Fiyat: " + rs.getDouble("fiyat") + " TL";
            
            jTextArea1.setText(bilgiler);
        } else {
            jTextArea1.setText("Oda Bilgileri:\n(Oda bulunamadı)");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String odaNo = jTextField1.getText().trim();
    String fiyatYazi = jTextField2.getText().replace("Fiyat:", "").trim();
    
    if (odaNo.isEmpty() || odaNo.equals("Oda Numarası:")) {
        JOptionPane.showMessageDialog(this, "Lütfen önce bir Oda Numarası giriniz!");
        return;
    }

    try (Connection con = DriverManager.getConnection(URL)) {
        StringBuilder query = new StringBuilder("UPDATE odalar SET ");
        boolean first = true;

        // --- DİNAMİK SORGU OLUŞTURMA ---
        if (!jComboBox1.getSelectedItem().equals("Seçiniz")) {
            query.append("tek_kisilik_yatak = ").append(jComboBox1.getSelectedItem());
            first = false;
        }

        if (!jComboBox2.getSelectedItem().equals("Seçiniz")) {
            if (!first) query.append(", ");
            query.append("cift_kisilik_yatak = ").append(jComboBox2.getSelectedItem());
            first = false;
        }

        if (!jComboBox3.getSelectedItem().equals("Seçiniz")) {
            if (!first) query.append(", ");
            String val = jComboBox3.getSelectedItem().equals("Var") ? "'true'" : "'false'";
            query.append("deniz_manzarasi = ").append(val);
            first = false;
        }

        if (!jComboBox4.getSelectedItem().equals("Seçiniz")) {
            if (!first) query.append(", ");
            String val = jComboBox4.getSelectedItem().equals("Var") ? "'true'" : "'false'";
            query.append("balkon = ").append(val);
            first = false;
        }

        if (!jComboBox5.getSelectedItem().equals("Seçiniz")) {
            if (!first) query.append(", ");
            String val = jComboBox5.getSelectedItem().equals("Var") ? "'true'" : "'false'";
            query.append("jakuzi = ").append(val);
            first = false;
        }

        if (!fiyatYazi.isEmpty() && !fiyatYazi.equals("Fiyat (TL)") && !fiyatYazi.equals("Fiyat:")) {
            if (!first) query.append(", ");
            query.append("fiyat = ").append(fiyatYazi);
            first = false;
        }

        // --- KRİTİK NOKTA: Hiçbir şey seçilmediyse ---
        if (first) {
            // SQL hatası almamak için dummy (etkisiz) bir güncelleme yapıyoruz: oda_no'yu kendisine eşitliyoruz.
            query.append("oda_no = oda_no"); 
        }

        query.append(" WHERE oda_no = ?");
        
        PreparedStatement pst = con.prepareStatement(query.toString());
        pst.setString(1, odaNo);
        
        if (pst.executeUpdate() > 0) {
            // Mesajı seçime göre belirle
            if (first) {
                JOptionPane.showMessageDialog(this, "Hiçbir şey değiştirilmedi.");
            } else {
                JOptionPane.showMessageDialog(this, "Oda " + odaNo + " güncellendi!");
            }
            
            temizle(); 
            jTextField1KeyReleased(null); 
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Hata: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed
// Formu sıfırlamak için yardımcı metod (Bunu class içinde uygun bir yere koy)
    private void temizle() {
    jTextField1.setText("Oda Numarası:");
    jTextField2.setText("Fiyat:"); // veya boş: jTextField2.setText("");
    jTextArea1.setText("Oda Bilgileri:");
    jComboBox1.setSelectedIndex(0); // "Seçiniz"e döner
    jComboBox2.setSelectedIndex(0);
    jComboBox3.setSelectedIndex(0);
    jComboBox4.setSelectedIndex(0);
    jComboBox5.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Personel p = new Personel("Test", 12345678916L, 0, null, "123");
            new YonetimGenel(p).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
