/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIYonetim;
import com.oybak.otel.Personel;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import com.oybak.otel.VeriTabani;

/**
 *
 * @author userxpc666
 */
public class YonetimOdaOzellik extends javax.swing.JFrame implements VeriTabani {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(YonetimOdaOzellik.class.getName());

    /**
     * Creates new form YonetimOdaOzellik
     */
    private Personel p;
    
    public YonetimOdaOzellik(Personel p) {
        initComponents();
        this.p=p;
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Kaydet");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Oda Bilgileri:");
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("Oda Numarası:");
        jTextField1.addActionListener(this::jTextField1ActionPerformed);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "1", "2", "3" }));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "1", "2", "3" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));
        jComboBox3.addActionListener(this::jComboBox3ActionPerformed);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seçiniz", "Var", "Yok" }));

        jLabel1.setText("Tek Kişilik Yatak");

        jLabel2.setText("Çift Kişilik Yatak");

        jLabel3.setText("Deniz Manzarasi");

        jLabel4.setText("Balkon");

        jLabel5.setText("Jakuzi");

        jLabel8.setText("Fiyat (TL)");

        jTextField2.setText("Fiyat:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField2))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          com.oybak.otel.GUIYonetim.YonetimGenel Genel = new com.oybak.otel.GUIYonetim.YonetimGenel(p);
       
       Genel.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        String odaNo = jTextField1.getText();
    if (odaNo.isEmpty()) {
        jTextArea1.setText("");
        return;
    }

    try {
        Connection con = DriverManager.getConnection(URL);
        String query = "SELECT * FROM odalar WHERE oda_no = ?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, odaNo);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            // Verileri çek ve True/False -> Var/Yok dönüşümü yap
            String dManzara = rs.getBoolean("deniz_manzarasi") ? "Var" : "Yok";
            String balkon = rs.getBoolean("balkon") ? "Var" : "Yok";
            String jakuzi = rs.getBoolean("jakuzi") ? "Var" : "Yok";

            String bilgiler = "Oda No: " + rs.getInt("oda_no") + "\n"
                            + "Tek Kişilik Yatak: " + rs.getInt("tek_kisilik_yatak") + "\n"
                            + "Çift Kişilik Yatak: " + rs.getInt("cift_kisilik_yatak") + "\n"
                            + "Deniz Manzarası: " + dManzara + "\n"
                            + "Balkon: " + balkon + "\n"
                            + "Jakuzi: " + jakuzi + "\n"
                            + "Fiyat: " + rs.getDouble("fiyat") + " TL";
            
            jTextArea1.setText(bilgiler);
        } else {
            jTextArea1.setText("Oda bulunamadı.");
        }
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Hata: " + e.getMessage());
    }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String odaNo = jTextField1.getText();
    // Kullanıcı "Fiyat:" yazısını silmeden sayı yazarsa onu temizleyelim
    String yeniFiyatStr = jTextField2.getText().replace("Fiyat:", "").trim(); 
    
    if (odaNo.isEmpty() || odaNo.equals("Oda Numarası:")) {
        JOptionPane.showMessageDialog(this, "Lütfen geçerli bir oda numarası giriniz!");
        return;
    }

    // HATA KONTROLÜ: Fiyat sadece sayı olmalı
    if (!yeniFiyatStr.isEmpty() && !yeniFiyatStr.matches("\\d+(\\.\\d+)?")) {
        JOptionPane.showMessageDialog(this, "Hata: Fiyat sadece sayı olmalıdır!", "Giriş Hatası", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection con = DriverManager.getConnection(URL);
        StringBuilder query = new StringBuilder("UPDATE odalar SET ");
        boolean first = true;

        // 1. Tek Kişilik Yatak Kontrolü
        if (!jComboBox1.getSelectedItem().toString().equals("Seçiniz")) {
            query.append("tek_kisilik_yatak = ").append(jComboBox1.getSelectedItem());
            first = false;
        }

        // 2. Çift Kişilik Yatak Kontrolü (Senin kodunda eksikti)
        if (!jComboBox2.getSelectedItem().toString().equals("Seçiniz")) {
            if (!first) query.append(", ");
            query.append("cift_kisilik_yatak = ").append(jComboBox2.getSelectedItem());
            first = false;
        }

        // 3. Deniz Manzarası Kontrolü (Boolean)
        if (!jComboBox3.getSelectedItem().toString().equals("Seçiniz")) {
            if (!first) query.append(", ");
            boolean val = jComboBox3.getSelectedItem().toString().equals("Var");
            query.append("deniz_manzarasi = '").append(val).append("'"); // SQLite boolean için tırnak gerekebilir
            first = false;
        }

        // 4. Balkon Kontrolü (Boolean - Senin kodunda eksikti)
        if (!jComboBox4.getSelectedItem().toString().equals("Seçiniz")) {
            if (!first) query.append(", ");
            boolean val = jComboBox4.getSelectedItem().toString().equals("Var");
            query.append("balkon = '").append(val).append("'");
            first = false;
        }

        // 5. Jakuzi Kontrolü (Boolean - Senin kodunda eksikti)
        if (!jComboBox5.getSelectedItem().toString().equals("Seçiniz")) {
            if (!first) query.append(", ");
            boolean val = jComboBox5.getSelectedItem().toString().equals("Var");
            query.append("jakuzi = '").append(val).append("'");
            first = false;
        }
        
        // 6. Fiyat Kontrolü
        if (!yeniFiyatStr.isEmpty()) {
            if (!first) query.append(", ");
            query.append("fiyat = ").append(yeniFiyatStr);
            first = false;
        }

        // Eğer hiçbir şey seçilmediyse sorguyu çalıştırma
        if (first) {
            JOptionPane.showMessageDialog(this, "Değiştirilecek bir alan seçmediniz.");
            return;
        }

        query.append(" WHERE oda_no = ?");
        
        PreparedStatement pst = con.prepareStatement(query.toString());
        pst.setString(1, odaNo);
        
        int sonuc = pst.executeUpdate();
        if (sonuc > 0) {
            JOptionPane.showMessageDialog(this, "Oda " + odaNo + " başarıyla güncellendi!");
            // Bilgileri TextArea'da güncellemek için metodu tekrar tetikle
            jTextField1KeyReleased(null); 
        } else {
            JOptionPane.showMessageDialog(this, "Oda bulunamadığı için güncelleme yapılamadı.");
        }
        
        con.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Veritabanı hatası: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Personel p = new Personel("Test", 12345678916L, 0, null, "123");
            new YonetimGenel(p).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
