/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIResepsiyon;
import com.oybak.otel.Hatalar;
import com.oybak.otel.Personel;
import com.oybakotel.GUI.OdaSecim;

/**
 *
 * @author onuro
 */
public class MusteriEkleme extends javax.swing.JFrame implements OdaSecim, Hatalar {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MusteriEkleme.class.getName());

    private Personel p;
    private int odaNo;
    private String otoGiris = null;
    private String otoCikis = null;
    
    public MusteriEkleme(Personel p, int odaNo) {
        this.p = p;
        this.odaNo = odaNo;
        initComponents();
    }
    
    // YENİ EKLENEN KURUCU METOT (2. ve 3. kişiler için çalışır, tarihleri alır)
    public MusteriEkleme(Personel p, int odaNo, String giris, String cikis) {
        this.p = p;
        this.odaNo = odaNo;
        this.otoGiris = giris;
        this.otoCikis = cikis;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTextField1.setText("Ad Soyad:");
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jTextField2.setText("TC Kimlik No:");
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField2FocusLost(evt);
            }
        });

        jLabel1.setText("Eklenecek Müşteri Bilgilerini Giriniz.");

        jButton1.setText("Müşteriyi Ekle");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Kapat");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String adSoyad = jTextField1.getText().trim();
        String tcNo = jTextField2.getText().trim();

        // 1. Boşluk ve varsayılan metin kontrolü
        if(adSoyad.isEmpty() || adSoyad.equals("Ad Soyad:") || tcNo.isEmpty() || tcNo.equals("TC Kimlik No:")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen müşteri adı ve TC kimlik numarasını tam giriniz!");
            return;
        }

        // 2. TC KİMLİK KONTROLÜ (VOID YÖNTEMİ)
        try {
            // tcKontrol void olduğu için sadece çalıştırıyoruz.
            tcKontrol(tcNo); 
        } catch (IllegalArgumentException ex) {
            // Eğer tcKontrol içinde bir hata bulunup fırlatılırsa kod buraya düşer
            // ve return diyerek veritabanı kayıt işlemlerini yapmadan anında dururuz.
            return; 
        }

        // EĞER TARİHLER HAFIZADA VARSA (Yani 2. veya 3. kişiyse)
        if (otoGiris != null && otoCikis != null) {
            // Tarih Seçim Ekranı'nı GÖRSEL OLARAK HİÇ AÇMADAN arka planda çalıştırıyoruz
            com.oybakotel.GUI.TarihSecimEkrani gizliEkran = new com.oybakotel.GUI.TarihSecimEkrani(p, odaNo, adSoyad, tcNo);
            gizliEkran.veritabaninaIsleVeKontrolEt(otoGiris, otoCikis); 
            this.dispose(); // Müşteri ekleme ekranını kapat
        } 
        // EĞER TARİHLER YOKSA (Yani odanın ilk müşterisiyse)
        else {
            // Tarihleri seçmesi için Tarih Seçim Ekranı'nı normal şekilde görünür olarak açıyoruz
            com.oybakotel.GUI.TarihSecimEkrani tarihEkrani = new com.oybakotel.GUI.TarihSecimEkrani(p, odaNo, adSoyad, tcNo);
            tarihEkrani.setLocationRelativeTo(null);
            tarihEkrani.setVisible(true);
            this.dispose(); // Müşteri ekleme ekranını kapat
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusGained
        // Eğer kutunun içinde varsayılan yazı varsa, kullanıcı tıklayınca içini temizle
        if (jTextField1.getText().equals("Ad Soyad:")) {
            jTextField1.setText("");
        }
    }//GEN-LAST:event_jTextField1FocusGained

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().isEmpty()) {
            jTextField1.setText("Ad Soyad:");
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
         // Eğer kutunun içinde varsayılan yazı varsa, kullanıcı tıklayınca içini temizle
        if (jTextField2.getText().equals("TC Kimlik No:")) {
        jTextField2.setText("");
        }
    }//GEN-LAST:event_jTextField2FocusGained

    private void jTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusLost
        if (jTextField2.getText().isEmpty()) {
        jTextField2.setText("TC Kimlik No:");
        }
    }//GEN-LAST:event_jTextField2FocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // OdaSecim interface'inden gelen metodu kullanıyoruz
        odaSecim(p); 
        this.dispose(); // Müşteri Ekleme ekranını kapat
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        Personel testPersoneli = new Personel("Test", 12345678910L, 0, null, "123");
        new MusteriEkleme(testPersoneli, -1).setVisible(true); // -1 test oda numarasıdır
     });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
