/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIResepsiyon;
import com.oybak.otel.Oda;
import com.oybak.otel.VeriTabani;
import com.oybak.otel.Yonetim;
import javax.swing.JOptionPane;
import com.oybak.otel.enums.UserRole;
/**
 *
 * @author onuro
 */
public class ParaAlma extends javax.swing.JFrame implements VeriTabani { //sd
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParaAlma.class.getName());

    //private com.oybak.otel.enums.UserRole aktifRol; // Mevcut rolü saklamak için
    
    /**
     * Creates new form ParaAlma
     */
    private UserRole aktifRol;
    
    public ParaAlma(UserRole aktifRol) {
        initComponents();
        doluOdalariYukle();
        odaComboBoxActionPerformed(null);
        this.aktifRol=aktifRol;
    }
    
    // Sınıfınızın içinde uygun bir yere bu metodu ekleyin:
private void doluOdalariYukle() {
    odaComboBox.removeAllItems(); // Önce eski verileri temizle
    
    // VeriTabani interface'ini implemente eden bir sınıf nesnesi (örneğin Resepsiyon)
    VeriTabani vt = new Yonetim("Geçici", "Geçici", 0L, 0.0, "Sistem","",""); 
    
    // Sadece durumu DOLU olan odaları getirir
    java.util.List<Oda> doluOdalar = vt.doluOdaListesi(); 

    for (Oda oda : doluOdalar) {
        // ComboBox'a oda numarasını ekliyoruz
        odaComboBox.addItem(String.valueOf(oda.getOdaNumarasi()));
    }
}

private double odenenMiktariGetir(int odaNo) {
    double odenen = 0.0;
    // guncel_musteriler tablosundan bu odaya ait kasa_katki değerini çekiyoruz
    String sql = "SELECT kasa_katki FROM guncel_musteriler WHERE oda_no = ?";
    
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection(com.oybak.otel.VeriTabani.URL);
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        // Veritabanında oda_no TEXT olarak tutulduğu için String'e çeviriyoruz[cite: 1]
        pstmt.setString(1, String.valueOf(odaNo)); 
        java.sql.ResultSet rs = pstmt.executeQuery();
        
        if (rs.next()) {
            odenen = rs.getDouble("kasa_katki");
        }
    } catch (Exception e) {
        System.out.println("Ödeme Sorgu Hatası: " + e.getMessage());
    }
    return odenen;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        odaComboBox = new javax.swing.JComboBox<>();
        fiyatText = new javax.swing.JLabel();
        odemeAl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        odaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        odaComboBox.addActionListener(this::odaComboBoxActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 31;
        gridBagConstraints.insets = new java.awt.Insets(6, 7, 0, 0);
        getContentPane().add(odaComboBox, gridBagConstraints);

        fiyatText.setText("     Fiyat: 0.0 TL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.insets = new java.awt.Insets(18, 7, 0, 0);
        getContentPane().add(fiyatText, gridBagConstraints);

        odemeAl.setText("Ödeme Al");
        odemeAl.addActionListener(this::odemeAlActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 29;
        gridBagConstraints.insets = new java.awt.Insets(26, 7, 27, 0);
        getContentPane().add(odemeAl, gridBagConstraints);

        jLabel1.setText("Ödeme Alacağınız Odayı Seçiniz");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.insets = new java.awt.Insets(12, 48, 0, 46);
        getContentPane().add(jLabel1, gridBagConstraints);

        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        getContentPane().add(jButton1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaComboBoxActionPerformed
    // 1. Seçilen nesneyi al ve boş değilse işleme başla
    Object secilen = odaComboBox.getSelectedItem();
    if (secilen == null) return;

    // 2. Doğrudan veritabanı bağlantısı açarak sorgu yap
    String sql = "SELECT fiyat FROM odalar WHERE oda_no = ?";
    
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection(com.oybak.otel.VeriTabani.URL);
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setInt(1, Integer.parseInt(secilen.toString()));
        
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                double fiyat = rs.getInt("fiyat");
                
                // rs.getDouble(), veritabanındaki değer NULL ise 0.0 döner.
                // Eğer veritabanında gerçekten NULL ise bunu kontrol edelim:
                if (rs.wasNull()) {
                    fiyatText.setText("Fiyat: Tanımlanmamış (NULL)");
                } else {
                    fiyatText.setText("Fiyat: " + fiyat + " TL");
                }
            } else {
                fiyatText.setText("Fiyat: Oda Bulunamadı");
            }
        }
    } catch (Exception e) {
        System.err.println("Hata: " + e.getMessage());
        fiyatText.setText("Fiyat: Bağlantı Hatası");
    }
    }//GEN-LAST:event_odaComboBoxActionPerformed

    private void odemeAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeAlActionPerformed
    // 1. Seçili odayı kontrol et
    Object secilen = odaComboBox.getSelectedItem();
    if (secilen == null) {
        javax.swing.JOptionPane.showMessageDialog(this, "Lütfen bir oda seçiniz!");
        return;
    }

    String odaNoStr = secilen.toString();
    double odaFiyati = 0.0;

    // 2. Interface metoduna güvenmek yerine doğrudan SQL ile fiyatı çek (Garantici Yöntem)
    String sql = "SELECT fiyat FROM odalar WHERE oda_no = ?";
    
    try (java.sql.Connection conn = java.sql.DriverManager.getConnection(com.oybak.otel.VeriTabani.URL);
         java.sql.PreparedStatement pstmt = conn.prepareStatement(sql)) {
        
        pstmt.setInt(1, Integer.parseInt(odaNoStr));
        
        try (java.sql.ResultSet rs = pstmt.executeQuery()) {
            if (rs.next()) {
                odaFiyati = rs.getDouble("fiyat");
            }
        }

        // 3. Fiyat kontrolü ve ödeme onayı
        if (odaFiyati > 0) {
            // Ödeme başarılı mesajı
            javax.swing.JOptionPane.showMessageDialog(this, 
                odaNoStr + " nolu odanın " + odaFiyati + " TL tutarındaki ödemesi alınmıştır.", 
                "Ödeme Başarılı", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // İsterseniz burada kasa güncelleme metodunuzu çağırabilirsiniz
            // ornek: resepsiyon.odemeAl(mevcutMusteri, secilenOda);

        } else {
            // Fiyat hala 0 geliyorsa veritabanı hücresinde sorun vardır
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Hata: Veritabanında " + odaNoStr + " nolu odanın fiyatı 0.0 veya boş görünüyor!\nLütfen DB Browser'dan kontrol edin.", 
                "Fiyat Hatası", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Hata oluştu: " + e.getMessage());
    }
    }//GEN-LAST:event_odemeAlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (aktifRol == com.oybak.otel.enums.UserRole.YONETIM) {
        // Yönetim sayfasına dön[cite: 1]
        com.oybak.otel.GUIYonetim.YonetimKasa yonetimGeri = new com.oybak.otel.GUIYonetim.YonetimKasa(aktifRol);
        yonetimGeri.setVisible(true);
    }   else {
        // Resepsiyon sayfasına dön[cite: 1]
        com.oybak.otel.GUIResepsiyon.ResepsiyonSayfa resepsiyonGeri = new com.oybak.otel.GUIResepsiyon.ResepsiyonSayfa(aktifRol);
        resepsiyonGeri.setVisible(true);
    }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                java.awt.EventQueue.invokeLater(() -> {
    // Test amaçlı varsayılan bir rol (örneğin YONETIM) gönderiyoruz
    new MusteriArama(com.oybak.otel.enums.UserRole.YONETIM).setVisible(true);
});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fiyatText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JComboBox<String> odaComboBox;
    private javax.swing.JButton odemeAl;
    // End of variables declaration//GEN-END:variables
}
