/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybak.otel.GUIResepsiyon;
import com.oybak.otel.Personel;
import com.oybak.otel.VeriTabani;
import com.oybak.otel.Resepsiyon;
import java.util.ArrayList;
import com.oybakotel.GUI.GeriButonu;
/**
 *
 * @author onuro
 */
public class ParaAlma extends javax.swing.JFrame implements VeriTabani, GeriButonu {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ParaAlma.class.getName());

    //private com.oybak.otel.enums.UserRole aktifRol; // Mevcut rolü saklamak için
    
    /**
     * Creates new form ParaAlma
     */
    private Personel p;
    
    public ParaAlma(Personel p) {
        initComponents();
        doluOdalariYukle();
        odaComboBoxActionPerformed(null);
        this.p = p;
    }
    
    // Sınıfınızın içinde uygun bir yere bu metodu ekleyin:
private void doluOdalariYukle() {
        odaComboBox.removeAllItems(); 
        
        ArrayList<String> odalar = Resepsiyon.getOdenmemisDoluOdalar();
        for (String oda : odalar) {
            odaComboBox.addItem(oda);
        }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        odaComboBox = new javax.swing.JComboBox<>();
        fiyatText = new javax.swing.JLabel();
        odemeAl = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        odaComboBox.setBackground(new java.awt.Color(51, 51, 255));
        odaComboBox.setForeground(new java.awt.Color(255, 255, 255));
        odaComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        odaComboBox.addActionListener(this::odaComboBoxActionPerformed);

        fiyatText.setText("Fiyat: 0.0 TL");

        odemeAl.setBackground(new java.awt.Color(51, 51, 255));
        odemeAl.setForeground(new java.awt.Color(255, 255, 255));
        odemeAl.setText("Ödeme Al");
        odemeAl.addActionListener(this::odemeAlActionPerformed);

        jLabel1.setText("Ödeme Alacağınız Odayı Seçiniz");

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Geri");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(76, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(odaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(odemeAl)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(fiyatText)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(odaComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(fiyatText, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(odemeAl, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void odaComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odaComboBoxActionPerformed
    Object secilen = odaComboBox.getSelectedItem();
        if (secilen == null) {
            fiyatText.setText("Fiyat: Seçili Oda Yok");
            return;
        }

        try {
            int odaNo = Integer.parseInt(secilen.toString());
            // Hesaplama işlemini arkaplana devrettik
            double toplamFiyat = Resepsiyon.hesaplaToplamFiyat(odaNo);
            
            if (toplamFiyat >= 0) {
                fiyatText.setText("Fiyat: " + toplamFiyat + " TL");
            } else {
                fiyatText.setText("Fiyat: Hata/Bulunamadı");
            }
        } catch (Exception e) {
            fiyatText.setText("Fiyat: Hata");
        }
    }//GEN-LAST:event_odaComboBoxActionPerformed

    private void odemeAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odemeAlActionPerformed
    Object secilen = odaComboBox.getSelectedItem();
        if (secilen == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Lütfen bir oda seçiniz!");
            return;
        }

        int odaNo = Integer.parseInt(secilen.toString());
        double odaFiyati = com.oybak.otel.Resepsiyon.hesaplaToplamFiyat(odaNo);

        if (odaFiyati > 0) {
            
            String islemSonucuMusteriTc = Resepsiyon.odemeAl(odaNo, odaFiyati);
            
            // Eğer islemSonucu null değilse işlem başarılı demektir (Bize ödeyenin TC'sini verir)
            if (islemSonucuMusteriTc != null) {
                javax.swing.JOptionPane.showMessageDialog(this, 
                    odaNo + " nolu odanın " + odaFiyati + " TL tutarındaki ödemesi alınmış ve ana müşteri (TC: " + islemSonucuMusteriTc + ") hesabına işlenmiştir.", 
                    "Ödeme Başarılı", 
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                
                logKayit(p.bilgileriYazdir() ," " + odaNo +" numaralı odanın ücreti " + islemSonucuMusteriTc + " TC'li müşteriden alındı");
                
                odaComboBox.removeItem(secilen);
                
                if (odaComboBox.getItemCount() > 0) {
                    odaComboBox.setSelectedIndex(0);
                } else {
                    fiyatText.setText("Fiyat: Ödenecek Oda Kalmadı");
                }
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Ödeme alınırken veritabanı hatası oluştu!", "Hata", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Hata: Veritabanında " + odaNo + " nolu odanın fiyatı 0.0 veya boş görünüyor!", 
                "Fiyat Hatası", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_odemeAlActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        geriButonu(p);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Personel p = new Personel("Test", 12345678916L, 0, null, "123");
            // Test amaçlı varsayılan bir rol (örneğin YONETIM) gönderiyoruz
            new MusteriArama(p).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fiyatText;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> odaComboBox;
    private javax.swing.JButton odemeAl;
    // End of variables declaration//GEN-END:variables
}
