/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

import com.oybak.otel.GUIMusteri.MusteriSayfasi;
import com.oybak.otel.enums.UserRole;
import static com.oybak.otel.enums.UserRole.MUSTERI;

import javafx.embed.swing.JFXPanel;
import javafx.scene.Scene;
import javafx.scene.media.Media;
import javafx.scene.media.MediaPlayer;
import javafx.scene.media.MediaView;
import javafx.application.Platform;
import java.io.File;
import java.awt.BorderLayout;

//vıaaa
/**
 *
 * @author ahmet
 */
public class Anasayfa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Anasayfa.class.getName());
    private UserRole aktifRol;
    
    /**
     * Creates new form Anasayfa
     */
    public Anasayfa() {
        initComponents();
        videoBaslat("C:\\Users\\ahmet\\Documents\\NetBeansProjects\\Oybak-Otel-Sistemi\\src\\main\\java\\images\\O.mp4");
    }
    
    private void videoBaslat(String dosyaYolu) {
    // 1. JFXPanel oluştur (Swing ile FX arasındaki köprü)
    final JFXPanel jfxPanel = new JFXPanel();
    
    // 2. videoPanel içine ekle
    videoPanel.removeAll(); // Varsa eski içeriği temizle
    videoPanel.add(jfxPanel, BorderLayout.CENTER);
    videoPanel.revalidate();
    videoPanel.repaint();

    // 3. JavaFX Thread'ini başlat
        Platform.runLater(() -> {
            try {
                File file = new File(dosyaYolu);
                String url = file.toURI().toString();
        
                Media media = new Media(url);
                MediaPlayer mediaPlayer = new MediaPlayer(media);
                MediaView mediaView = new MediaView(mediaPlayer);

                // 1. Bir StackPane oluştur (JavaFX Layout bileşeni)
                // StackPane, içine konulan bileşeni otomatik olarak merkeze yerleştirir.
                javafx.scene.layout.StackPane root = new javafx.scene.layout.StackPane();
                root.getChildren().add(mediaView);
                
                // 2. Sahneyi (Scene) bu root panel ile oluştur
                Scene scene = new Scene(root);

                // 3. HATA ALDIĞIN YER: 
                // JFXPanel yerine doğrudan Sahne'nin (Scene) genişliğine bağla.
                mediaView.fitWidthProperty().bind(scene.widthProperty());
                mediaView.fitHeightProperty().bind(scene.heightProperty());
        
                // Oranı korumak istersen true, tam sığsın istersen false yap
                mediaView.setPreserveRatio(true); 

                jfxPanel.setScene(scene);
                mediaPlayer.play();
        
            } catch (Exception e) {
                System.err.println("Hata: " + e.getMessage());
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        musteri = new javax.swing.JButton();
        otelGiris = new javax.swing.JButton();
        videoPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        musteri.setBackground(new java.awt.Color(51, 51, 255));
        musteri.setForeground(new java.awt.Color(255, 255, 255));
        musteri.setText("Müşteri Girişi");
        musteri.addActionListener(this::musteriActionPerformed);

        otelGiris.setBackground(new java.awt.Color(51, 51, 255));
        otelGiris.setForeground(new java.awt.Color(255, 255, 255));
        otelGiris.setText("Otel Giriş");
        otelGiris.addActionListener(this::otelGirisActionPerformed);

        videoPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(musteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(otelGiris, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(videoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(musteri, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otelGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(0, 49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void musteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musteriActionPerformed
          aktifRol = MUSTERI;

        TarihSecimEkrani tarihEkrani = new TarihSecimEkrani(aktifRol);
        // 3. Ekranı ortala ve görünür yap
        tarihEkrani.setLocationRelativeTo(null); 
        tarihEkrani.setVisible(true);
        this.dispose(); // Anasayfayı kapat        /
    }//GEN-LAST:event_musteriActionPerformed

    private void otelGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otelGirisActionPerformed
        GirisPopopGUI popup = new GirisPopopGUI(); 
        popup.setLocationRelativeTo(this); // Pop-up'ın ana pencerenin tam ortasında fırlamasını sağlar
        popup.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_otelGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Anasayfa().setVisible(true));
    }

    public UserRole getAktifRol() {
        return aktifRol;
    }

    public void setAktifRol(UserRole aktifRol) {
        this.aktifRol = aktifRol;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton musteri;
    private javax.swing.JButton otelGiris;
    private javax.swing.JPanel videoPanel;
    // End of variables declaration//GEN-END:variables
}
