/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

/**
 *
 * @author ahmet
 */
public class Anasayfa extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Anasayfa.class.getName());

    /**
     * Creates new form Anasayfa
     */
    public Anasayfa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Musteri = new javax.swing.JButton();
        resepsiyon = new javax.swing.JButton();
        müdüriyet = new javax.swing.JButton();
        teknikPeronel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Musteri.setBackground(new java.awt.Color(51, 51, 255));
        Musteri.setForeground(new java.awt.Color(255, 255, 255));
        Musteri.setText("Müşteri Girişi");
        Musteri.addActionListener(this::MusteriActionPerformed);

        resepsiyon.setBackground(new java.awt.Color(51, 51, 255));
        resepsiyon.setForeground(new java.awt.Color(255, 255, 255));
        resepsiyon.setText("Resepsiyon Girişi");
        resepsiyon.addActionListener(this::resepsiyonActionPerformed);

        müdüriyet.setBackground(new java.awt.Color(51, 51, 255));
        müdüriyet.setForeground(new java.awt.Color(255, 255, 255));
        müdüriyet.setText("Müdüriyet Girişi");
        müdüriyet.addActionListener(this::müdüriyetActionPerformed);

        teknikPeronel.setBackground(new java.awt.Color(51, 51, 255));
        teknikPeronel.setForeground(new java.awt.Color(255, 255, 255));
        teknikPeronel.setText("Teknik Peronel Girişi");
        teknikPeronel.addActionListener(this::teknikPeronelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(resepsiyon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teknikPeronel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(müdüriyet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Musteri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(Musteri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resepsiyon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(müdüriyet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(teknikPeronel)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MusteriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MusteriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MusteriActionPerformed

    private void resepsiyonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resepsiyonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resepsiyonActionPerformed

    private void müdüriyetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_müdüriyetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_müdüriyetActionPerformed

    private void teknikPeronelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teknikPeronelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_teknikPeronelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Anasayfa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Musteri;
    private javax.swing.JButton müdüriyet;
    private javax.swing.JButton resepsiyon;
    private javax.swing.JButton teknikPeronel;
    // End of variables declaration//GEN-END:variables
}
