/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

/**
 *
 * @author userxpc666
 */
public class OdaSecimEkrani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OdaSecimEkrani.class.getName());

    /**
     * Creates new form YonetimOdalar
     */
    public OdaSecimEkrani() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        j101 = new javax.swing.JButton();
        j102 = new javax.swing.JButton();
        j103 = new javax.swing.JButton();
        j104 = new javax.swing.JButton();
        j105 = new javax.swing.JButton();
        j201 = new javax.swing.JButton();
        j202 = new javax.swing.JButton();
        j203 = new javax.swing.JButton();
        j204 = new javax.swing.JButton();
        j205 = new javax.swing.JButton();
        j301 = new javax.swing.JButton();
        j302 = new javax.swing.JButton();
        j303 = new javax.swing.JButton();
        j304 = new javax.swing.JButton();
        j305 = new javax.swing.JButton();
        j401 = new javax.swing.JButton();
        j402 = new javax.swing.JButton();
        j403 = new javax.swing.JButton();
        j404 = new javax.swing.JButton();
        j405 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Filtreleme = new javax.swing.JComboBox<>();
        Geri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        textField1.setText("textField1");
        textField1.addActionListener(this::textField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 6, 10, 10));

        j101.setLabel("101");
        j101.addActionListener(this::j101ActionPerformed);
        jPanel1.add(j101);

        j102.setLabel("102");
        jPanel1.add(j102);

        j103.setLabel("103");
        j103.addActionListener(this::j103ActionPerformed);
        jPanel1.add(j103);

        j104.setLabel("104");
        jPanel1.add(j104);

        j105.setLabel("105");
        jPanel1.add(j105);

        j201.setText("201");
        jPanel1.add(j201);

        j202.setText("202");
        jPanel1.add(j202);

        j203.setText("203");
        jPanel1.add(j203);

        j204.setText("204");
        j204.addActionListener(this::j204ActionPerformed);
        jPanel1.add(j204);

        j205.setText("205");
        jPanel1.add(j205);

        j301.setText("301");
        jPanel1.add(j301);

        j302.setText("302");
        j302.setToolTipText("");
        jPanel1.add(j302);

        j303.setText("303");
        jPanel1.add(j303);

        j304.setText("304");
        jPanel1.add(j304);

        j305.setText("305");
        j305.setMaximumSize(new java.awt.Dimension(50, 50));
        j305.setMinimumSize(new java.awt.Dimension(50, 50));
        j305.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(j305);

        j401.setText("401");
        jPanel1.add(j401);

        j402.setText("402");
        jPanel1.add(j402);

        j403.setText("403");
        jPanel1.add(j403);

        j404.setText("404");
        jPanel1.add(j404);

        j405.setText("405");
        jPanel1.add(j405);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ODA SEÇİNİZ");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        Filtreleme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "1 Kişilik", "2 Kişilik", "3 Kişilik", "4 Kişilik" }));

        Geri.setText("GERİ");

        jLabel2.setText("FİLTRELEME");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(Geri)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Geri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void j101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j101ActionPerformed

    private void j103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j103ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j103ActionPerformed

    private void j204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j204ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_j204ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OdaSecimEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Filtreleme;
    private javax.swing.JButton Geri;
    private javax.swing.JButton j101;
    private javax.swing.JButton j102;
    private javax.swing.JButton j103;
    private javax.swing.JButton j104;
    private javax.swing.JButton j105;
    private javax.swing.JButton j201;
    private javax.swing.JButton j202;
    private javax.swing.JButton j203;
    private javax.swing.JButton j204;
    private javax.swing.JButton j205;
    private javax.swing.JButton j301;
    private javax.swing.JButton j302;
    private javax.swing.JButton j303;
    private javax.swing.JButton j304;
    private javax.swing.JButton j305;
    private javax.swing.JButton j401;
    private javax.swing.JButton j402;
    private javax.swing.JButton j403;
    private javax.swing.JButton j404;
    private javax.swing.JButton j405;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

    
   
// Bu fonksiyon dışarıdan (filtreleme ekranından) çağrılacak
public void filtreyiUygula(int kapasite) {
    // Tüm oda butonlarını bir diziye veya listeye alırsan işin kolaylaşır
    // Şimdilik mantığı anlaman için örnek:
    
    if (kapasite == 0) { // "Hepsi" seçildiyse
        
    } else {
        // Burada normalde veritabanına bakılır ama manuel test için:
        // Eğer seçilen kapasite oda kapasitesine uymuyorsa gizle
        // Örn: jButton1 (101 nolu oda) 2 kişilikse ve kapasite 3 seçildiyse:
        // jButton1.setVisible(false);
    }
}
 

}
