/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

import java.awt.Color;
import com.oybak.otel.VeriTabani;
import com.oybak.otel.Oda;
import com.oybak.otel.Personel;
import static com.oybak.otel.enums.OdaDurumu.BAKIMDA;
import static com.oybak.otel.enums.OdaDurumu.DOLU;
import static com.oybak.otel.enums.OdaDurumu.MUSAIT;
import com.oybak.otel.enums.UserRole;
    
/**
 *
 * @author userxpc666
 */
public class OdaSecimEkrani extends javax.swing.JFrame implements OdalaraGecis, VeriTabani, GeriButonu{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OdaSecimEkrani.class.getName());
    

    /**
     * Creates new form YonetimOdalar
     */
    
    private Personel p;
    
    public OdaSecimEkrani(Personel p) {
        this.p = p;
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
        
        odalariRenklendir(); 
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        j101 = new javax.swing.JButton();
        j102 = new javax.swing.JButton();
        j103 = new javax.swing.JButton();
        j104 = new javax.swing.JButton();
        j105 = new javax.swing.JButton();
        j201 = new javax.swing.JButton();
        j202 = new javax.swing.JButton();
        j203 = new javax.swing.JButton();
        j204 = new javax.swing.JButton();
        j205 = new javax.swing.JButton();
        j301 = new javax.swing.JButton();
        j302 = new javax.swing.JButton();
        j303 = new javax.swing.JButton();
        j304 = new javax.swing.JButton();
        j305 = new javax.swing.JButton();
        j401 = new javax.swing.JButton();
        j402 = new javax.swing.JButton();
        j403 = new javax.swing.JButton();
        j404 = new javax.swing.JButton();
        j405 = new javax.swing.JButton();
        Filtreleme = new javax.swing.JComboBox<>();
        Geri = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        textField1.setText("textField1");
        textField1.addActionListener(this::textField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel2.setBackground(new java.awt.Color(51, 102, 255));

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));
        jPanel1.setLayout(new java.awt.GridLayout(4, 6, 10, 10));

        j101.setLabel("101");
        j101.addActionListener(this::j101ActionPerformed);
        jPanel1.add(j101);

        j102.setLabel("102");
        j102.addActionListener(this::j102ActionPerformed);
        jPanel1.add(j102);

        j103.setLabel("103");
        j103.addActionListener(this::j103ActionPerformed);
        jPanel1.add(j103);

        j104.setLabel("104");
        j104.addActionListener(this::j104ActionPerformed);
        jPanel1.add(j104);

        j105.setLabel("105");
        j105.addActionListener(this::j105ActionPerformed);
        jPanel1.add(j105);

        j201.setText("201");
        j201.addActionListener(this::j201ActionPerformed);
        jPanel1.add(j201);

        j202.setText("202");
        j202.addActionListener(this::j202ActionPerformed);
        jPanel1.add(j202);

        j203.setText("203");
        j203.addActionListener(this::j203ActionPerformed);
        jPanel1.add(j203);

        j204.setText("204");
        j204.addActionListener(this::j204ActionPerformed);
        jPanel1.add(j204);

        j205.setText("205");
        j205.addActionListener(this::j205ActionPerformed);
        jPanel1.add(j205);

        j301.setText("301");
        j301.addActionListener(this::j301ActionPerformed);
        jPanel1.add(j301);

        j302.setText("302");
        j302.setToolTipText("");
        j302.addActionListener(this::j302ActionPerformed);
        jPanel1.add(j302);

        j303.setText("303");
        j303.addActionListener(this::j303ActionPerformed);
        jPanel1.add(j303);

        j304.setText("304");
        j304.addActionListener(this::j304ActionPerformed);
        jPanel1.add(j304);

        j305.setText("305");
        j305.setMaximumSize(new java.awt.Dimension(50, 50));
        j305.setMinimumSize(new java.awt.Dimension(50, 50));
        j305.setPreferredSize(new java.awt.Dimension(50, 50));
        j305.addActionListener(this::j305ActionPerformed);
        jPanel1.add(j305);

        j401.setText("401");
        j401.addActionListener(this::j401ActionPerformed);
        jPanel1.add(j401);

        j402.setText("402");
        j402.addActionListener(this::j402ActionPerformed);
        jPanel1.add(j402);

        j403.setText("403");
        j403.addActionListener(this::j403ActionPerformed);
        jPanel1.add(j403);

        j404.setText("404");
        j404.addActionListener(this::j404ActionPerformed);
        jPanel1.add(j404);

        j405.setText("405");
        j405.addActionListener(this::j405ActionPerformed);
        jPanel1.add(j405);

        Filtreleme.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hepsi", "1 Kişilik", "2 Kişilik", "3 Kişilik", "4 Kişilik" }));

        Geri.setText("GERİ");
        Geri.addActionListener(this::GeriActionPerformed);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("FİLTRELEME");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ODA SEÇİNİZ");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Geri)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(112, 112, 112))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(Filtreleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Geri, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void j101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j101ActionPerformed
        odalaraGecis(101, p); 
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j101ActionPerformed

    private void j103ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j103ActionPerformed
        odalaraGecis(103, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j103ActionPerformed

    private void j204ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j204ActionPerformed
        odalaraGecis(204, p);       
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j204ActionPerformed

    private void j102ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j102ActionPerformed
        odalaraGecis(102, p);     
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j102ActionPerformed

    private void j104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j104ActionPerformed
        odalaraGecis(104, p);     
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j104ActionPerformed

    private void j105ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j105ActionPerformed
        odalaraGecis(105, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j105ActionPerformed

    private void j201ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j201ActionPerformed
        odalaraGecis(201, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j201ActionPerformed

    private void j202ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j202ActionPerformed
        odalaraGecis(202, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j202ActionPerformed

    private void j203ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j203ActionPerformed
        odalaraGecis(203, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j203ActionPerformed

    private void j205ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j205ActionPerformed
        odalaraGecis(205, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j205ActionPerformed

    private void j301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j301ActionPerformed
        odalaraGecis(301, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j301ActionPerformed

    private void j302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j302ActionPerformed
        odalaraGecis(302, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j302ActionPerformed

    private void j303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j303ActionPerformed
        odalaraGecis(303, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j303ActionPerformed

    private void j304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j304ActionPerformed
        odalaraGecis(304, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j304ActionPerformed

    private void j305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j305ActionPerformed
        odalaraGecis(305, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j305ActionPerformed

    private void j401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j401ActionPerformed
        odalaraGecis(401, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j401ActionPerformed

    private void j402ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j402ActionPerformed
        odalaraGecis(402, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j402ActionPerformed

    private void j403ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j403ActionPerformed
        odalaraGecis(403, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j403ActionPerformed

    private void j404ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j404ActionPerformed
        odalaraGecis(404, p);   
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j404ActionPerformed

    private void j405ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j405ActionPerformed
        odalaraGecis(405, p);    
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_j405ActionPerformed

    private void GeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeriActionPerformed
        geriButonu(p);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_GeriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            Personel p = new Personel("Test", 12345678916L, 0, null, "123");
            new OdaSecimEkrani(p).setVisible(true); // Sondaki fazladan ')' silindi
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Filtreleme;
    private javax.swing.JButton Geri;
    private javax.swing.JButton j101;
    private javax.swing.JButton j102;
    private javax.swing.JButton j103;
    private javax.swing.JButton j104;
    private javax.swing.JButton j105;
    private javax.swing.JButton j201;
    private javax.swing.JButton j202;
    private javax.swing.JButton j203;
    private javax.swing.JButton j204;
    private javax.swing.JButton j205;
    private javax.swing.JButton j301;
    private javax.swing.JButton j302;
    private javax.swing.JButton j303;
    private javax.swing.JButton j304;
    private javax.swing.JButton j305;
    private javax.swing.JButton j401;
    private javax.swing.JButton j402;
    private javax.swing.JButton j403;
    private javax.swing.JButton j404;
    private javax.swing.JButton j405;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

    
   
// Bu fonksiyon dışarıdan (filtreleme ekranından) çağrılacak
public void filtreyiUygula(int kapasite) {
    // Tüm oda butonlarını bir diziye veya listeye alırsan işin kolaylaşır
    // Şimdilik mantığı anlaman için örnek:
    
    if (kapasite == 0) { // "Hepsi" seçildiyse
        
    } else {
        // Burada normalde veritabanına bakılır ama manuel test için:
        // Eğer seçilen kapasite oda kapasitesine uymuyorsa gizle
        // Örn: jButton1 (101 nolu oda) 2 kişilikse ve kapasite 3 seçildiyse:
        // jButton1.setVisible(false);
    }
}
private void odalariRenklendir() {
        javax.swing.JButton[] odaButonlari = {
            j101, j102, j103, j104, j105, 
            j201, j202, j203, j204, j205,
            j301, j302, j303, j304, j305,
            j401, j402, j403, j404, j405
        };

        for (javax.swing.JButton buton : odaButonlari) {
            if (buton == null || buton.getText() == null || buton.getText().trim().isEmpty()) continue;

            try {
                int odaNo = Integer.parseInt(buton.getText().trim()); 
                Oda oda = odaBilgileri(odaNo); 

                if (oda != null && oda.getOdaDurumu() != null) {
                    // Renklerin görünmesi için gereken standart ayarlar
                    buton.setContentAreaFilled(true);
                    buton.setOpaque(true);
                    buton.setBorderPainted(true);

                    switch (oda.getOdaDurumu()) {
                        case MUSAIT -> {
                            buton.setBackground(new Color(46, 204, 113)); // Yeşil
                            buton.setForeground(Color.WHITE);
                            buton.setEnabled(true);
                        }
                        case DOLU -> {
                            buton.setBackground(new Color(231, 76, 60)); // Kırmızı
                            buton.setForeground(Color.WHITE);
                            buton.setEnabled(true); // Gri olmaması için true bıraktık
                        }
                        case BAKIMDA -> {
                            buton.setBackground(new Color(241, 196, 15)); // Sarı
                            buton.setForeground(Color.BLACK);
                            buton.setEnabled(true); // Gri olmaması için true bıraktık
                        }
                        default -> buton.setBackground(Color.LIGHT_GRAY);
                    }
                } else {
                    buton.setBackground(Color.LIGHT_GRAY);
                }
            } catch (Exception e) {
                // Hata durumunda buton varsayılan renginde kalsın
            }
        }
    }
}
