/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

/**
 *
 * @author userxpc666
 */
public class OdaSecimEkrani extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OdaSecimEkrani.class.getName());

    /**
     * Creates new form YonetimOdalar
     */
    public OdaSecimEkrani() {
        initComponents();
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); // Uygulamayı tam ekran açar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textField1 = new java.awt.TextField();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        textField1.setText("textField1");
        textField1.addActionListener(this::textField1ActionPerformed);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(MAXIMIZED_BOTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 6, 10, 10));

        jButton1.setLabel("100");
        jButton1.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jButton1);

        jButton2.setLabel("101");
        jPanel1.add(jButton2);

        jButton3.setLabel("102");
        jPanel1.add(jButton3);

        jButton4.setLabel("103");
        jPanel1.add(jButton4);

        jButton5.setLabel("104");
        jPanel1.add(jButton5);

        jButton6.setLabel("105");
        jPanel1.add(jButton6);

        jButton7.setLabel("200");
        jPanel1.add(jButton7);

        jButton8.setText("201");
        jPanel1.add(jButton8);

        jButton9.setText("202");
        jPanel1.add(jButton9);

        jButton10.setText("203");
        jPanel1.add(jButton10);

        jButton11.setText("204");
        jPanel1.add(jButton11);

        jButton12.setText("205");
        jPanel1.add(jButton12);

        jButton13.setText("300");
        jPanel1.add(jButton13);

        jButton14.setText("301");
        jPanel1.add(jButton14);

        jButton15.setText("302");
        jButton15.setToolTipText("");
        jPanel1.add(jButton15);

        jButton16.setText("303");
        jPanel1.add(jButton16);

        jButton17.setText("304");
        jPanel1.add(jButton17);

        jButton18.setText("305");
        jButton18.setMaximumSize(new java.awt.Dimension(50, 50));
        jButton18.setMinimumSize(new java.awt.Dimension(50, 50));
        jButton18.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel1.add(jButton18);

        jButton19.setText("400");
        jPanel1.add(jButton19);

        jButton20.setText("401");
        jPanel1.add(jButton20);

        jButton21.setText("402");
        jPanel1.add(jButton21);

        jButton22.setText("403");
        jPanel1.add(jButton22);

        jButton23.setText("404");
        jPanel1.add(jButton23);

        jButton24.setText("405");
        jPanel1.add(jButton24);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ODA SEÇİNİZ");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new OdaSecimEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private java.awt.TextField textField1;
    // End of variables declaration//GEN-END:variables

    
   
// Bu fonksiyon dışarıdan (filtreleme ekranından) çağrılacak
public void filtreyiUygula(int kapasite) {
    // Tüm oda butonlarını bir diziye veya listeye alırsan işin kolaylaşır
    // Şimdilik mantığı anlaman için örnek:
    
    if (kapasite == 0) { // "Hepsi" seçildiyse
        jButton1.setVisible(true); // Örnek oda 101
        jButton2.setVisible(true); // Örnek oda 102
    } else {
        // Burada normalde veritabanına bakılır ama manuel test için:
        // Eğer seçilen kapasite oda kapasitesine uymuyorsa gizle
        // Örn: jButton1 (101 nolu oda) 2 kişilikse ve kapasite 3 seçildiyse:
        // jButton1.setVisible(false);
    }
}
 

}
