/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.oybakotel.GUI;

/**
 *
 * @author Yunus
 */
public class TarihSecimEkrani extends javax.swing.JFrame {
    
    private com.toedter.calendar.JDateChooser girisTakvim;
    private com.toedter.calendar.JDateChooser cikisTakvim;
    private com.oybak.otel.enums.UserRole aktifRol;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TarihSecimEkrani.class.getName());

    /**
     * Creates new form TarihSecimEkrani
     */
    public TarihSecimEkrani(com.oybak.otel.enums.UserRole rol) {
        this.aktifRol=rol;
        initComponents();
        
        
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH); //tam ekran yapmak için
        
        // JFrame'in ana taşıyıcısının layout'unu GridBagLayout yapıyoruz
        this.getContentPane().setLayout(new java.awt.GridBagLayout());
    
        // Buradaki "anaPanel" tüm elemanlarını içine koyduğun panelin adıdır
        // Eğer adını farklı yaptıysan onu yazmalısın.
        this.add(AnaPanel, new java.awt.GridBagConstraints());
        
        // Takvim nesnelerini oluşturuyoruz
    girisTakvim = new com.toedter.calendar.JDateChooser();
    cikisTakvim = new com.toedter.calendar.JDateChooser();

    // Giriş paneline (pnlGiris) takvimi tam sığacak şekilde ekle
    pnlGiris.setLayout(new java.awt.BorderLayout());
    pnlGiris.add(girisTakvim, java.awt.BorderLayout.CENTER);

    // Çıkış paneline (pnlCikis) takvimi tam sığacak şekilde ekle
    pnlCikis.setLayout(new java.awt.BorderLayout());
    pnlCikis.add(cikisTakvim, java.awt.BorderLayout.CENTER);

    // Görselin anında ekrana yansıması için panelleri yenile
    pnlGiris.revalidate();
    pnlGiris.repaint();
    pnlCikis.revalidate();
    pnlCikis.repaint();
    
    // --- TAKVİM KODLARI BİTİŞİ ---
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        AnaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnlGiris = new javax.swing.JPanel();
        pnlCikis = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        devamEt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        AnaPanel.setBackground(new java.awt.Color(255, 255, 255));
        AnaPanel.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Konaklama Tarihleri ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 33;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 94, 0, 6);
        AnaPanel.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Giriş Tarihi :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(22, 33, 0, 0);
        AnaPanel.add(jLabel2, gridBagConstraints);

        pnlGiris.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnlGirisLayout = new javax.swing.GroupLayout(pnlGiris);
        pnlGiris.setLayout(pnlGirisLayout);
        pnlGirisLayout.setHorizontalGroup(
            pnlGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        pnlGirisLayout.setVerticalGroup(
            pnlGirisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        AnaPanel.add(pnlGiris, gridBagConstraints);

        pnlCikis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout pnlCikisLayout = new javax.swing.GroupLayout(pnlCikis);
        pnlCikis.setLayout(pnlCikisLayout);
        pnlCikisLayout.setHorizontalGroup(
            pnlCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 184, Short.MAX_VALUE)
        );
        pnlCikisLayout.setVerticalGroup(
            pnlCikisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 184;
        gridBagConstraints.ipady = 28;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 4, 0, 0);
        AnaPanel.add(pnlCikis, gridBagConstraints);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Çıkış Tarihi :");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(78, 23, 0, 0);
        AnaPanel.add(jLabel3, gridBagConstraints);

        devamEt.setText("Devam Et");
        devamEt.addActionListener(this::devamEtActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 109, 48, 0);
        AnaPanel.add(devamEt, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnaPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 551, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(AnaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void devamEtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devamEtActionPerformed
        // 1. Takvimlerden seçilen tarihleri alıyoruz
    java.util.Date giris = girisTakvim.getDate();
    java.util.Date cikis = cikisTakvim.getDate();
    java.util.Date bugun = new java.util.Date(); // Bugünün tarihi

    // KONTROL 1: Boşluk Kontrolü (Kullanıcı tarih seçmeyi unutmuş mu?)
    if (giris == null || cikis == null) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Lütfen konaklama yapacağınız giriş ve çıkış tarihlerini seçiniz!", 
            "Eksik Bilgi", 
            javax.swing.JOptionPane.WARNING_MESSAGE);
        return; // Hata varsa kodu burada kes, aşağıya inme
    }

    // KONTROL 2: Geçmiş Tarih Kontrolü (Giriş bugünden önce olamaz)
    // (Saat farklarını yoksaymak için bugünün tam tarihinden bir gün öncesiyle kıyaslarız ama basitçe şöyle yapabiliriz)
    // Not: Date nesnesi saati de tuttuğu için tam gün kıyası biraz daha uzundur, şimdilik en temel halini yazıyoruz.
    if (giris.before(new java.util.Date(bugun.getTime() - (1000 * 60 * 60 * 24)))) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Giriş tarihi geçmiş bir tarih olamaz!", 
            "Geçersiz Tarih", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // KONTROL 3: Çıkış Tarihi Kontrolü (Çıkış, girişten önce veya aynı gün olamaz)
    if (cikis.before(giris) || cikis.equals(giris)) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Çıkış tarihi, giriş tarihinden en az 1 gün sonra olmalıdır!", 
            "Mantık Hatası", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
        return;
    }

    // --- BÜTÜN KONTROLLERDEN GEÇTİYSE BURAYA ULAŞIR ---
    
    // Test amaçlı, doğru tarihler seçildiyse ekrana yazdıralım:
    System.out.println("Başarılı! Giriş: " + giris + " | Çıkış: " + cikis);
    
    // Müşteriyi Oda Seçim Ekranına yolla ve rolünü de beraberinde götür
    com.oybakotel.GUI.OdaSecimEkrani odaEkrani = new com.oybakotel.GUI.OdaSecimEkrani(aktifRol);
    odaEkrani.setVisible(true);
    
    // İşimiz biten bu tarih ekranını kapatalım
    this.dispose();

    }//GEN-LAST:event_devamEtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        new TarihSecimEkrani(com.oybak.otel.enums.UserRole.MUSTERI).setVisible(true); //test etmek için müşteri
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnaPanel;
    private javax.swing.JButton devamEt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlCikis;
    private javax.swing.JPanel pnlGiris;
    // End of variables declaration//GEN-END:variables
}
